package com.example.hive.Models;

import android.graphics.Bitmap;
import android.util.Base64;
import android.util.Log;

import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.SetOptions;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.journeyapps.barcodescanner.BarcodeEncoder;

import java.io.ByteArrayOutputStream;
import java.util.HashMap;

/**
 * store QR Code in db. QR code generation function is in Event.java.
 * This class is to convert QR code from bitmap -> base64,
 * store it in the db, and make it retrievable from the db
 */
public class QRCode {
    private String firebaseID;

    /**
     * constructor
     * @param firebaseID
     */
    public QRCode(String firebaseID) {
        this.firebaseID = firebaseID;
    }

    public String getFirebaseID() {
        return firebaseID;
    }

    public void setFirebaseID(String firebaseID) {
        this.firebaseID = firebaseID;
    }

    /**
     * Generates a QR code image from event id that is automatically generated by firestore.
     *
     * @param width  The width of the QR code.
     * @param height The height of the QR code.
     * @return The generated QR code as a Bitmap.
     * @throws WriterException If an error occurs during QR code generation.
     */
    public Bitmap generateQRCode(int width, int height) throws WriterException {
        if (firebaseID == null || firebaseID.isEmpty()) {
            throw new IllegalStateException("firebaseID is not set. Unable to generate QR code.");
        }
        String data = firebaseID;
        MultiFormatWriter writer = new MultiFormatWriter();
        BitMatrix matrix = writer.encode(data, BarcodeFormat.QR_CODE, width, height);
        BarcodeEncoder encoder = new BarcodeEncoder();
        return encoder.createBitmap(matrix);
    }

    /**
     * Convert QR code bitmap to string
     * @param bitmap
     * @return base64 string
     */
    private static String convertBitmapToBase64(Bitmap bitmap) {
        ByteArrayOutputStream stream = new ByteArrayOutputStream();
        bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream);
        return Base64.encodeToString(stream.toByteArray(), Base64.DEFAULT);
    }

    /**
     * Saves the qr string to database.
     * Note that the eventId is the auto generated id of the event document in the db.
     * @param qrCodeBitmap
     * @param eventId
     */
    public static void saveQRToDb(Bitmap qrCodeBitmap, String eventId) {
        String qrCodeBase64 = convertBitmapToBase64(qrCodeBitmap);
        FirebaseFirestore db = FirebaseFirestore.getInstance();
        db.collection("events").document(eventId)
                .set(new HashMap<String, Object>() {{
                    put("qrCode", qrCodeBase64);
                }}, SetOptions.merge())
                .addOnSuccessListener(v -> Log.d("Firestore", "QR Code saved to db"))
                .addOnFailureListener(e -> Log.e("Firestore", "Error saving QR code to db"));
    }

    /**
     * retrieve the QR code from the db.
     * can be used to confirm that the qr hash is in the db.
     * @param eventId
     * @param callback
     */
    public static void retrieveQRCodeFromDb(String eventId, QRCodeCallback callback) {
        FirebaseFirestore db = FirebaseFirestore.getInstance();
        db.collection("events").document(eventId).get()
                .addOnSuccessListener(documentSnapshot -> {
                    if (documentSnapshot.exists()) {
                        String qrCodeBase64 = documentSnapshot.getString("qrCode");
                        callback.onQRCodeRetrieved(qrCodeBase64);
                    } else {
                        callback.onError(new Exception("Document DNE"));
                    }
                })
                .addOnFailureListener(callback::onError);
    }

    /**
     * Can use onQRCodeRetrieved to handle the base64 str
     */
    public interface QRCodeCallback {
        void onQRCodeRetrieved(String qrCodeBase64);
        void onError(Exception e);
    }

    /**
     * Admin functionality: remove QR code from db.
     * @param eventId
     */
    public static void  removeQRCodeFromDb(String eventId) {
        FirebaseFirestore db = FirebaseFirestore.getInstance();
        db.collection("events").document(eventId)
                .update("qrCode", null);
    }
}
